"""
Run from /workspaces/neuro-san-studio:
    python write_patched_hocon.py
Writes the patched HOCON to disk without clipboard or triple-quote conflicts.
"""
import pathlib

DEST = pathlib.Path("registries/generated/ravi_digital_twin_multiagent_system.hocon")

# Triple-quote marker used in HOCON multiline strings — kept as a variable
# so Python never sees it as a string delimiter.
TQ = '"""'

lines = [
'{',
'    include "registries/aaosa.hocon"',
'    include "registries/llm_config.hocon"',
'',
'    "metadata": {',
'        "name": "rAvI Digital Twin Multiagent System",',
'        "description": "A living digital twin that learns an author\'s voice from all their content and generates new content that sounds exactly like them.",',
'        "sample_queries": [',
'            "Ingest this URL and extract the author\'s voice signature: https://example.com/article",',
'            "Generate a 500-word blog post on creative burnout in my voice.",',
'            "Research the topic of creative voice development and add to my knowledge base.",',
'            "What does my current voice profile look like?"',
'        ]',
'    },',
'',
'    "content_dir": "./content/ingested/"',
'',
'    "instructions_prefix": ' + TQ,
'You are part of the rAvI digital twin multiagent system.',
'Only answer inquiries directly within your area of expertise.',
'Do not try to help with other matters.',
'Do not mention what you cannot do. Only mention what you can do.',
TQ + ',',
'',
'    "tools": [',
'        {',
'            "name": "top_agent",',
'            "function": {',
'                "description": "Entry point for the rAvI digital twin system. Routes all user requests to the appropriate specialist agent."',
'            },',
'            "instructions": ${instructions_prefix} ' + TQ,
'You are the front door of the rAvI digital twin multiagent system.',
'Your job is to understand the user\'s request and route it to the correct agent.',
'',
'Route as follows:',
'- Any request to GENERATE content, write a post, write an article, draft anything,',
'  or produce output in Ravi\'s voice -> content_generator FIRST.',
'  Do NOT route generation requests to author_profile_integration.',
'- Any request to ingest a URL -> url_ingestor',
'- Any request to ingest a file or local document -> doc_reader',
'- Any request to extract a voice signature from text -> voice_and_style_extractor',
'- Any request to VIEW or QUERY the author\'s voice profile -> author_profile_integration',
'- Any request to research a topic or build the knowledge base -> web_resources_modeling',
'- Any request to check data store status, content ledger, memory, or knowledge graph -> memory_layer_manager',
'- Any request to monitor social media profiles -> social_media_monitor',
'',
'Always delegate. If ambiguous, pick the most likely agent and proceed.',
TQ + ',',
'            "command": ${aaosa_command},',
'            "tools": [',
'                "memory_layer_manager",',
'                "author_profile_integration",',
'                "content_generator",',
'                "url_ingestor",',
'                "doc_reader",',
'                "voice_and_style_extractor",',
'                "web_resources_modeling",',
'                "social_media_monitor"',
'            ]',
'        },',
'        {',
'            "name": "memory_layer_manager",',
'            "function": {',
'                "description": "Central state store for the rAvI system. Manages the Content Ledger, VoiceProfile, Knowledge Graph, and Session Log."',
'            },',
'            "instructions": ${instructions_prefix} ' + TQ,
'You are the central state store for the entire rAvI network.',
'',
'STARTUP SEQUENCE (run before serving any other request):',
'1. Call memory_query_tool with operation health_check.',
'   - If status OK, proceed normally.',
'   - If error, STOP and report: "MEMORY STORE UNAVAILABLE: ChromaDB connection failed."',
'2. If healthy, call doc_reader with operation scan_and_ingest.',
'',
'On write: confirm success and return record ID(s). If write fails, return explicit error.',
'On read: return exact object with version and timestamp, or NOT_FOUND. Never fabricate records.',
TQ + ',',
'            "tools": [',
'                "doc_reader",',
'                "author_profile_integration",',
'                "content_generator",',
'                "stateless_agent",',
'                "memory_query_tool"',
'            ]',
'        },',
'        {',
'            "name": "doc_reader",',
'            "function": {',
'                "description": "Scans content_dir and ingests all PDFs and supported documents. Also accepts on-demand file paths."',
'            },',
'            "instructions": ${instructions_prefix} ' + TQ,
'You are the local document ingestion agent for the rAvI system.',
'On startup (called with operation scan_and_ingest):',
'1. Scan ./content/ingested/',
'2. Call memory_query_tool with operation get_content_ledger to skip already-ingested files.',
'3. For each new file: extract text, clean it, pass to voice_and_style_extractor,',
'   then call memory_query_tool with operation log_ingested_content.',
'   Capture the returned record ID. If write fails, log error and skip.',
'4. Return an INGESTION RECEIPT listing files found, added, failed, and record IDs.',
'On-demand: follow same steps for the provided file only. Always return a receipt.',
TQ + ',',
'            "command": ${aaosa_command},',
'            "tools": [',
'                "/tools/pdf_rag",',
'                "/tools/file_reader",',
'                "voice_and_style_extractor",',
'                "memory_query_tool"',
'            ]',
'        },',
'        {',
'            "name": "memory_query_tool",',
'            "function": {',
'                "description": "Persistent ChromaDB store. Operations: health_check, get_content_ledger, log_ingested_content, get_voice_profile, upsert_voice_profile, query_knowledge_graph, add_knowledge_entry, log_session_event. All writes return explicit success/failure."',
'            },',
'            "class": "memory_query_tool.MemoryQueryTool"',
'        },',
'        {',
'            "name": "author_profile_integration",',
'            "function": ${aaosa_call},',
'            "instructions": ${instructions_prefix} ' + TQ,
'You integrate and maintain the author\'s master voice profile.',
'Merge new voice signatures via memory_query_tool operation upsert_voice_profile.',
'Retrieve profiles via get_voice_profile. If NOT_FOUND, report explicitly.',
'Do NOT fabricate a profile from conversation context.',
TQ + ',',
'            "command": ${aaosa_command},',
'            "tools": [',
'                "voice_and_style_extractor",',
'                "url_ingestor",',
'                "web_resources_modeling",',
'                "memory_query_tool"',
'            ]',
'        },',
'        {',
'            "name": "content_generator",',
'            "function": ${aaosa_call},',
'            "instructions": ${instructions_prefix} ' + TQ,
'You generate original content in the author\'s voice.',
'1. Call memory_query_tool get_voice_profile. If NOT_FOUND, STOP and tell user to ingest samples first.',
'2. Call memory_query_tool query_knowledge_graph. If empty, warn user in output.',
'3. Generate draft conditioned on VoiceProfile: match rhythm, vocabulary, tonal scores, structure.',
'4. Pass to stateless_agent for review. Revise if score < 0.75. Max 3 cycles.',
'5. Call memory_query_tool log_session_event. Return record ID as receipt.',
'Always return: final draft, scorecard, session log ID, any KG warnings.',
TQ + ',',
'            "command": ${aaosa_command},',
'            "tools": [',
'                "stateless_agent",',
'                "author_profile_integration",',
'                "memory_query_tool"',
'            ]',
'        },',
'        {',
'            "name": "stateless_agent",',
'            "function": ${aaosa_call},',
'            "instructions": ${instructions_prefix} ' + TQ,
'You are the voice authenticity review gate.',
'Score drafts on: syntactic match, lexical match, tonal match, structural match (each 0.0-1.0).',
'Composite = average. If < 0.75 return with revision instructions. If >= 0.75 approve with scorecard.',
TQ + ',',
'            "command": ${aaosa_command},',
'            "tools": [',
'                "/tools/openai_code_interpreter"',
'            ]',
'        },',
'        {',
'            "name": "voice_and_style_extractor",',
'            "function": ${aaosa_call},',
'            "instructions": ${instructions_prefix} ' + TQ,
'Extract the author\'s voice signature and return structured JSON:',
'- Average sentence length and rhythm with 3 examples',
'- Top 10 characteristic words, top 5 signature phrases',
'- Tonal scores: Humor, Intimacy, Urgency, Certainty, Empathy (0-10)',
'- Opening type, closing type, punctuation personality, core worldview statement',
'Pass completed JSON to author_profile_integration.',
TQ + ',',
'            "command": ${aaosa_command},',
'            "tools": [',
'                "/tools/openai_code_interpreter"',
'            ]',
'        },',
'        {',
'            "name": "url_ingestor",',
'            "function": ${aaosa_call},',
'            "instructions": ${instructions_prefix} ' + TQ,
'Ingest content from URLs. Fetch, clean, identify metadata, pass to voice_and_style_extractor,',
'then call memory_query_tool log_ingested_content. If write fails, report explicitly.',
'Return INGESTION RECEIPT with URL, content type, word count, Content Ledger ID.',
'Handle batch input sequentially.',
TQ + ',',
'            "command": ${aaosa_command},',
'            "tools": [',
'                "/tools/ddgs_search",',
'                "voice_and_style_extractor",',
'                "memory_query_tool"',
'            ]',
'        },',
'        {',
'            "name": "web_resources_modeling",',
'            "function": ${aaosa_call},',
'            "instructions": ${instructions_prefix} ' + TQ,
'Research topics and build the knowledge base.',
'Generate 3 search queries, retrieve results, score relevance and credibility,',
'extract summaries and key claims, store top 5 via memory_query_tool add_knowledge_entry.',
'Return RESEARCH RECEIPT with topic, sources evaluated, KG entries written, record IDs, errors.',
TQ + ',',
'            "command": ${aaosa_command},',
'            "tools": [',
'                "/tools/ddgs_search",',
'                "doc_reader",',
'                "memory_query_tool"',
'            ]',
'        },',
'        {',
'            "name": "social_media_monitor",',
'            "function": ${aaosa_call},',
'            "instructions": ${instructions_prefix} ' + TQ,
'Monitor author\'s public social profiles (only where active = true).',
'Retrieve posts since last_monitored, run voice delta analysis, log batches,',
'update last_monitored timestamp. Return summary of new posts and tonal flags.',
TQ + ',',
'            "command": ${aaosa_command},',
'            "tools": [',
'                "/tools/ddgs_search",',
'                "voice_and_style_extractor",',
'                "memory_query_tool"',
'            ]',
'        }',
'    ]',
'}',
]

content = "\n".join(lines) + "\n"
DEST.write_text(content)
total = len(lines)
last3 = "\n".join(lines[-3:])
print(f"Written {total} lines to {DEST}")
print(f"Last 3 lines:\n{last3}")